title: Still Time Studio
description: >
  瞑想アプリとゲームの開発スタジオ
baseurl: ""
url: "https://kazunakka.github.io"

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty

# Jekyll processing
source: .
destination: _site

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - README.md

# theme: minima
# plugins:
#   - jekyll-feed